### PR TITLE
[+] add new stat activity grid report

### PR DESCRIPTION
**Pull request by pmpetit**
Hello,
One of my collegue Manu G. has created a new report on stat-activity, to match our needs.
I have tested it, i think we should share.

Example
image

### CODE REVIEW

**Comment by pmpetit** [comment]
This dashboard represents the number of sessions taht are executing the query, just like oracle does in oem (Oracle Entreprise Mngt).
For example in yellow at 9h55, we can see that 4 sessions were executing 
SELECT /* getReception etc... (the second query)

It is a well known dashboard in oracle world.

**Comment by pashagolub** [comment]
Thanks a lot for clarifications!

**Comment by pashagolub** [comment]
During testing this grid I got an error from Grafana:
```
Templating
Failed to upgrade legacy queries Datasource pgwatch-metrics was not found
Templating [dbname]
Error updating options: Datasource pgwatch-metrics was not found
```

Did you see such messages on a fresh installs with your dashboards?

**Comment by pashagolub** [comment]
I noticed that only your `dashboartd.json` contains `"datasource": "pgwatch-metrics"` string. Can this be the reason?

**Comment by pashagolub** [comment]
I noticed that only your `dashboartd.json` contains `"datasource": "pgwatch-metrics"` string. Can this be the reason?

**Comment by pmpetit** [comment]
I have a check

**Comment by pashagolub** [comment]
I'm not sure what am I doing wrong but it's just doesn't work:
image

Would you please try to reproduce my steps. In the local pgwatch2 repo execute:
```
$ ./build-docker-postgres.sh

$  docker run -d --restart=unless-stopped --name pw2 -p 3000:3000 -p 8080:
8080 -p 127.0.0.1:5432:5432  -e PW2_TESTDB=true   cybertec/pgwatch2-postgres:latest
```
Then try to open http://localhost:3000/d/stat-activity/stat-activity

**Comment by pmpetit** [comment]
face errors, looknig for a workaround
```log
go: downloading github.com/coreos/go-systemd v0.0.0-20191104093116-d3cd4ed1dbcf
go: downloading github.com/hashicorp/consul/api v1.12.0
go: downloading github.com/influxdata/influxdb1-client v0.0.0-20220302092344-a9ab5670611c
go: downloading github.com/jessevdk/go-flags v1.5.0
go: downloading github.com/jmoiron/sqlx v1.3.4
go: downloading github.com/lib/pq v1.10.4
go: downloading github.com/marpaia/graphite-golang v0.0.0-20190519024811-caf161d2c2b1
go: downloading github.com/op/go-logging v0.0.0-20160315200505-970db520ece7
go: downloading github.com/prometheus/client_golang v1.12.1
go: downloading github.com/samuel/go-zookeeper v0.0.0-20201211165307-7117e9ea2414
go: downloading github.com/shirou/gopsutil/v3 v3.22.2
go: downloading github.com/shopspring/decimal v1.3.1
go: downloading go.etcd.io/etcd/client/v2 v2.305.2
go: downloading go.etcd.io/etcd v3.3.27+incompatible
go: downloading golang.org/x/crypto v0.0.0-20220321153916-2c7772ba3064
go: downloading gopkg.in/yaml.v2 v2.4.0
pgwatch2.go:35:2: github.com/coreos/go-systemd@v0.0.0-20191104093116-d3cd4ed1dbcf: Get "https://proxy.golang.org/github.com/coreos/go-systemd/@v/v0.0.0-20191104093116-d3cd4ed1dbcf.zip": x509: certificate signed by unknown authority
patroni.go:12:2: github.com/hashicorp/consul/api@v1.12.0: Get "https://proxy.golang.org/github.com/hashicorp/consul/api/@v/v1.12.0.zip": x509: certificate signed by unknown authority
pgwatch2.go:36:2: github.com/influxdata/influxdb1-client@v0.0.0-20220302092344-a9ab5670611c: Get "https://proxy.golang.org/github.com/influxdata/influxdb1-client/@v/v0.0.0-20220302092344-a9ab5670611c.zip": x509: certificate signed by unknown authority
pgwatch2.go:37:2: github.com/jessevdk/go-flags@v1.5.0: Get "https://proxy.golang.org/github.com/jessevdk/go-flags/@v/v1.5.0.zip": x509: certificate signed by unknown authority
pgwatch2.go:38:2: github.com/jmoiron/sqlx@v1.3.4: Get "https://proxy.golang.org/github.com/jmoiron/sqlx/@v/v1.3.4.zip": x509: certificate signed by unknown authority
pgwatch2.go:39:2: github.com/lib/pq@v1.10.4: Get "https://proxy.golang.org/github.com/lib/pq/@v/v1.10.4.zip": x509: certificate signed by unknown authority
pgwatch2.go:40:2: github.com/marpaia/graphite-golang@v0.0.0-20190519024811-caf161d2c2b1: Get "https://proxy.golang.org/github.com/marpaia/graphite-golang/@v/v0.0.0-20190519024811-caf161d2c2b1.zip": x509: certificate signed by unknown authority
pgwatch2.go:41:2: github.com/op/go-logging@v0.0.0-20160315200505-970db520ece7: Get "https://proxy.golang.org/github.com/op/go-logging/@v/v0.0.0-20160315200505-970db520ece7.zip": x509: certificate signed by unknown authority
prom.go:12:2: github.com/prometheus/client_golang@v1.12.1: Get "https://proxy.golang.org/github.com/prometheus/client_golang/@v/v1.12.1.zip": x509: certificate signed by unknown authority
prom.go:13:2: github.com/prometheus/client_golang@v1.12.1: Get "https://proxy.golang.org/github.com/prometheus/client_golang/@v/v1.12.1.zip": x509: certificate signed by unknown authority
patroni.go:13:2: github.com/samuel/go-zookeeper@v0.0.0-20201211165307-7117e9ea2414: Get "https://proxy.golang.org/github.com/samuel/go-zookeeper/@v/v0.0.0-20201211165307-7117e9ea2414.zip": x509: certificate signed by unknown authority
pgwatch2.go:42:2: github.com/shirou/gopsutil/v3@v3.22.2: Get "https://proxy.golang.org/github.com/shirou/gopsutil/v3/@v/v3.22.2.zip": x509: certificate signed by unknown authority
pgwatch2.go:32:2: github.com/shirou/gopsutil/v3@v3.22.2: Get "https://proxy.golang.org/github.com/shirou/gopsutil/v3/@v/v3.22.2.zip": x509: certificate signed by unknown authority
pgwatch2.go:43:2: github.com/shirou/gopsutil/v3@v3.22.2: Get "https://proxy.golang.org/github.com/shirou/gopsutil/v3/@v/v3.22.2.zip": x509: certificate signed by unknown authority
pgwatch2.go:33:2: github.com/shirou/gopsutil/v3@v3.22.2: Get "https://proxy.golang.org/github.com/shirou/gopsutil/v3/@v/v3.22.2.zip": x509: certificate signed by unknown authority
pgwatch2.go:44:2: github.com/shopspring/decimal@v1.3.1: Get "https://proxy.golang.org/github.com/shopspring/decimal/@v/v1.3.1.zip": x509: certificate signed by unknown authority
patroni.go:14:2: go.etcd.io/etcd/client/v2@v2.305.2: Get "https://proxy.golang.org/go.etcd.io/etcd/client/v2/@v/v2.305.2.zip": x509: certificate signed by unknown authority
patroni.go:15:2: go.etcd.io/etcd@v3.3.27+incompatible: Get "https://proxy.golang.org/go.etcd.io/etcd/@v/v3.3.27+incompatible.zip": x509: certificate signed by unknown authority
pgwatch2.go:45:2: golang.org/x/crypto@v0.0.0-20220321153916-2c7772ba3064: Get "https://proxy.golang.org/golang.org/x/crypto/@v/v0.0.0-20220321153916-2c7772ba3064.zip": x509: certificate signed by unknown authority
pgwatch2.go:46:2: gopkg.in/yaml.v2@v2.4.0: Get "https://proxy.golang.org/gopkg.in/yaml.v2/@v/v2.4.0.zip": x509: certificate signed by unknown authority
```

**Comment by pmpetit** [comment]
image
it is because there is no activity on the database.....

**Comment by pmpetit** [comment]
Hi,
i have troubleshooted, it is ok now:

- add this metric to default "FULL" template (we were using only the preset-config.yaml file), that's why you could not see it in your test.
- troubleshoot some typo (epoch was missing in the metric)

i have tested with your docker run command line (and pgbench):
image

**Comment by pashagolub** [comment]
Excellent! Thank you.

**Pull request merged**
