### PR TITLE
[+] use predefined Grafana dashboards `uid`, fixes #474

### LINKED ISSUE #474: broken link in some dashboards
image

### PR DESCRIPTION
**Pull request by pashagolub**
[+] add `uid` to v8 dashboards
[-] fix `import_all.sh` and `set_up_grafana_dashboards*.sh`
[-] fix `delete_all_old_pw2_dashes.sh`

### CODE REVIEW

**Comment by yanchenko-igor** [comment]
looks good, but maybe we should fix influxdb and prometheus dashboards as well?

**Comment by pashagolub** [comment]
Influxdb fixed by `set_up_grafana_dashboards.sh`. I just didn't update JSONs since it doesn't matter here.
Prometheus needs a separate issue and branch, I believe. The provisioning of its dashboards made somehow different

**Comment by yanchenko-igor** [comment]
> Influxdb fixed by `set_up_grafana_dashboards.sh`. I just didn't update JSONs since it doesn't matter here. Prometheus needs a separate issue and branch, I believe. The provisioning of its dashboards made somehow different

Well, if we deploy pgwatch2 using helm chart, we don't run the script, we are using the json files.

**Comment by pashagolub** [comment]
Oh, I didn't know that! Good point!
@yanchenko-igor, would you please point me to how we do provisioning with helm charts?

**Comment by yanchenko-igor** [comment]
> Oh, I didn't know that! Good point! @yanchenko-igor, would you please point me to how we do provisioning with helm charts?

It's just adding the json files to Configmap https://github.com/cybertec-postgresql/pgwatch2/blob/helmchart/helm-chart/templates/grafana-dashboards.yaml

**Comment by pashagolub** [comment]
Thanks! Will add `uid` for influx jsons as well

**Comment by yanchenko-igor** [comment]
What about `linkUrl` in other json files?

**Comment by pashagolub** [comment]
Crap! :-(

**Review by yanchenko-igor — APPROVED** [review]

**Pull request merged**
