### PR TITLE
Helm Chart

### LINKED ISSUE #133: Feature request - a Kubernetes Helm chart for deployment
Hey there, 

I'm needing to deploy pgwatch2 only pw2+confg postgres into a kubernetes cluster.. It will collect metrics from multiples RDS Postgres deployments for multiples environemts , and persist to a sigle and external Influxdb alerady running.

Is there any one using some Helm charts to deploy pw2?

### PR DESCRIPTION
**Pull request by jinnerbichler**
We are currently deploying pgwatch2 (with Prometheus as datastore) to our Kubernetes cluster using a Helm chart as deployment tool.
Therefore, we created a proper Helm chart, which we want to contribute to this project.

Closes #133 #165 

Greetings from [Salzburg Research](https://www.salzburgresearch.at/)

### CODE REVIEW

**Comment by kmoppel** [comment]
@jinnerbichler Great news! Worked out of the box:) Only one small change request - could you please mention in the readme that by default the chart is using "prometheus" and show where to look for to have standard metrics storage behaviour (most people use PG / Influx metric storage). Thanks a lot!

**Comment by jinnerbichler** [comment]
@kmoppel Changed the datastore in the mentioned example to `postgres`.

**Comment by kmoppel** [comment]
Thanks a lot!

**Comment by zhihongd** [comment]
@jinnerbichler We want to use the exporter with our existing postgres config db and grafana.  Looks like the helm charts only work with pgwatch2-nonroot or pgwatch2-postgres, both have all components added to the image.  Have you guys tried the helm charts with pgwatch2-daemon image?  Thanks.

**Pull request merged**
